### PR TITLE
remove new github workflow from upstream

### PR DESCRIPTION
**Pull request by mpastyl**
Remove the new action from upstream that builds and runs tests.

AFAIU, even before my recent merges, we couldn't really build and test the fork autonomously (at least not without renaming all our imports from  "import go.fd.io/govpp/... " to "import github.com/EMnify/govpp/..."). The idea is that we only need the fork to import the api bindings.

@mejedi Maybe a stupid question but why did we rename the module name of our fork to `module github.com/EMnify/govpp`?
Wouldn't it work fine if we kept it as in upstream? Then we wouldn't have this problem here. Would `replace git.fd.io/govpp.git => github.com/EMnify/govpp v.x.y.z` on EDA continue to work?

### CODE REVIEW

**Comment by mejedi** [comment]
> Wouldn't it work fine if we kept it as in upstream?

Not really sure if it will work if the import path didn’t agree with the module self-identification. Care to try it out?

**Comment by mpastyl** [comment]
Sure, let me try

**Comment by mpastyl** [comment]
@mejedi It works. But to make it work I had to replace, on EDA, all imports to `git.fd.io/govpp.git` with `go.fd.io/govpp` and regenerate all the vpp binapi. Is it ok to go with that?

**Comment by mpastyl** [comment]
Closing this. Re-used the upstream version for the module name so that github actions work.
Opened a PR on EDA to patch things on that side https://github.com/EMnify/EDA/pull/801

**Pull request closed without merging**
